### ISSUE TITLE
Feature request: Integration with AltMetrics (Twitter, Mendeley, blogs, etc)

### ISSUE THREAD

**Issue by slhill** [OpenKnowledgeSpace/KnowledgeSpace#2]
I suggest adding a new [Twitter] data source in a new pane that would call Twitter search to see the latest tweets about a concept. This often provides useful links to interesting papers curated by the twittersphere - YMMV!

Jeff Grethe's good idea: One way to do this (as we don on SciCrunch) is to tie into AltMetrics - see https://scicrunch.org/neuinfo/literature/search?q=neuron%20generation for an example.  That would give information on mentions in more than just Twitter - but also Mendeley, blogs, etc.

**Comment by tgbugs** [comment]
Closing for now. One potential way to address this the quality issue would be to use crossref even data by searching for dois from literature.
