### ISSUE TITLE
How to comply with citation policies of content sources

### ISSUE THREAD

**Issue by MBAbrams** [OpenKnowledgeSpace/KnowledgeSpace#28]
Each of the content sources in KS has a specific policy for how content used from their source should be cited. How do we deal with this? Do we simply have a tab on the website with the citation policy for each source or is there a ay to automate this?

**Comment by tgbugs** [comment]
There was a suggestion that we provide bibtex or similar based on the data that the user wants. Another was to provide a doi to the collection which could hold the citation data.
