### ISSUE TITLE
Get brain region description that is in the Summary section

### ISSUE THREAD

**Issue by Tsolmongerel** [OpenKnowledgeSpace/KnowledgeSpace#37]
We are using KnowledgeSpace summary information in the Atlas Viewer.

When I want to see all information about Thalamus region, I use following link:
https://knowledge-space.org/NeuroKS/index.php/pages/view/MBA:549

To get the particular information in the Data Space section, I use:
https://knowledge-space.org/NeuroKS/index.php/API/summary/MBA:549

Likewise, to get the text description in the Summary section using the API, what URL or link should I use?

Neuroinformatics, Human Brain Project

**Comment by mdupont** [comment]
Bumping this one, I'll provide more information.

In our [Atlas Viewer](https://nip.humanbrainproject.eu/atlas/ ) we are consuming your summary API (for instance https://knowledge-space.org/API/summary/MBA:549 ).

We would like to have the description of the brain region in the API output. Currently it isn't there. It is what appears under the "Description" section on https://knowledge-space.org/wiki/MBA:549

**Comment by mdupont** [comment]
+1

**Comment by mdupont** [comment]
Any info on this feature?

**Comment by tgbugs** [comment]
We have exported these to [an ontology file](https://github.com/SciCrunch/NIF-Ontology/blob/master/ttl/generated/ksdesc-defs.ttl) which has been loaded back into scigraph. You can get them from the definitions section of http://trinity.neuinfo.org:9000/scigraph/vocabulary/id/NIFCELL:sao862606388 which will also contain the summary section (assuming there is a definition at all) even if one isn't defined in https://github.com/OpenKnowledgeSpace/ksdesc/. You can substitute NIFCELL:sao862606388 for [MBA:549](http://trinity.neuinfo.org:9000/scigraph/vocabulary/id/MBA:549) in the original example. Please let me know if this will work for you.
