### ISSUE TITLE
general performance issues

### ISSUE THREAD

**Issue by tgbugs** [OpenKnowledgeSpace/KnowledgeSpace#43]
1) latency: mirroring, cdn
~~2) asynchronous loading: e.g. the literature summary graph~~
3) elasticsearch aggregation: slow dataspace loading

**Comment by wawong** [comment]
2) Asynchronous loading for literature summary graph is available for testing on the staging server at http://kaa.neuinfo.org/

The page will not be delayed by the literature summary graph anymore.
