### ISSUE TITLE
rename the organization for branding reasons

### ISSUE THREAD

**Issue by tgbugs** [OpenKnowledgeSpace/KnowledgeSpace#49]
We have previously pigeon-holed ourselves with neuroscience branding, we should change the name of the organization to prevent this (eg `ResearchKnowledgeSpace`, `OpenKnowledgeSpace` or `Knowledge-Space` if available). However doing so without warning may break builds that expect a repo at https://github.com/NeuroscienceKnowledgeSpace/KnowledgeSpace.git (or methodsOntology.git). This issue is for alerting and coordination for all KS repos.

@MFSY @jgrethe @wawong @samuel-kerrien

**Comment by jgrethe** [comment]
+1 

I like Open Knowledge Space...

**Comment by tgbugs** [comment]
@jgrethe @MFSY @samuel-kerrien We are going to change the organization name to OpenKnowledgeSpace at 9am your time tomorrow August 24th. Will be in touch then to make sure everything goes smoothly.

**Comment by MFSY** [comment]
Thank you for the notice. I'll be in office at that time ready to update our Scigraph config files.

**Comment by tgbugs** [comment]
@wawong when you get a chance can you update any references you have to point to OpenKnowledgeSpace now?

@MFSY Change has been made ping me here if there are any issues.

**Comment by MFSY** [comment]
I updated the references we have for methodsOntology repo. There is no issues for now. I'll let you know if there is any. Thank you.
