### ISSUE TITLE
Consider use of standard ontologies

### ISSUE THREAD

**Issue by mellybelly** [OpenKnowledgeSpace/KnowledgeSpace#54]
There are many neuro-relevant community standard ontologies and vocabularies present within the OBO Foundry:
http://www.obofoundry.org/
Particularly relevant are the Uberon anatomy ontology and Cell type ontology:
http://www.obofoundry.org/ontology/cl.html
http://www.obofoundry.org/ontology/uberon.html
www.uberon.org

These are used extensively by large scale projects such as EBI, LINCS, ENCODE, FANTOM, nextProt, Bgee, and many others and incorporate many neuroscience concepts and sources.

Given INCF's regular interest in hosting ontology workshops, I was surprised that none of these had been incorporated into the knowledgespace as yet. I think you might find that the integration of different vocabularies and standardization might be easier with the use of ontologies. 

Let us know if you need help.

**Comment by cmungall** [comment]
I note you bring in duplicate concepts from NIFGA:

 * https://knowledge-space.org/NeuroKS/index.php/pages/view/UBERON:0001890
 * https://knowledge-space.org/NeuroKS/index.php/pages/view/NIFGA:birnlex_1509

AFAICT NIFGA is no longer maintained. All concepts from NIFGA should be in Uberon (although some such as regional-part-of-Xs, introduced originally for Protege browsing, have been obsoleted)

For some reason the NIFGA hierarchy view says 'has part' but it is a partonomy just like the uberon one. Both should just say 'part of'

**Comment by tgbugs** [comment]
Thanks for catching the issue with has part/part of. At the moment we are just loading NIFSTD so uberon is already loaded, and the [uberon/NIFGA issue](https://github.com/SciCrunch/NIF-Ontology/issues/35) is on my todo list for the NIFSTD 3.0 release. Once https://github.com/OpenKnowledgeSpace/KnowledgeSpace/issues/25 is complete I will start compiling an list of ontologies that we may want to use for KS independent of those used in NIF.
