### ISSUE TITLE
API summary endpoint fails with PHP error

### ISSUE THREAD

**Issue by mdupont** [OpenKnowledgeSpace/KnowledgeSpace#56]
Error seems to come from https://github.com/OpenKnowledgeSpace/KnowledgeSpace/blob/master/NeuroKS/application/views/api/view_summary.php#L28

To reproduce:
- go to https://knowledge-space.org/NeuroKS/index.php/API/summary/MBA:549
- notice the HTML output with the PHP error backtrack displayed on top of the JSON response

Since there is HTML when we expect a JSON response, the parsing of the JSON fails (when called from https://nip.humanbrainproject.eu/atlas/#/ )

It seems that when trying to access $result->result->resultCount, the second "result" object doesn't exist or is not an object. Guarding against that case should fix it by checking that it is an object containing the expected field.

**Comment by tgbugs** [comment]
It looks like the error isn't showing up now, but when this was first posted I remember seeing it as well. If it comes up again could you take a screenshot and record the exact time so we can check logs please? Thanks!

**Comment by wawong** [comment]
I close this ticket for now if there is no objection. Otherwise please reopen this ticket.
