### ISSUE TITLE
Add links from data sources to the sources' terms of use

### ISSUE THREAD

**Issue by MBAbrams** [OpenKnowledgeSpace/KnowledgeSpace#64]
I have most of the links and will forward to Willy. Waiting for 3 sources to give me the information since it is not clearly visible on the website.

**Comment by wawong** [comment]
Mathew, I just want to follow up on this one. Do we have the information about their terms of use?

**Comment by MBAbrams** [comment]
I have shared the googledoc with the information with you (e-mail).

**Comment by wawong** [comment]
I created a JSON file for loading the "terms of use" information.

https://github.com/OpenKnowledgeSpace/KnowledgeSpace/blob/master/NeuroKS/application/config/terms_of_use.json
