### ISSUE TITLE
Integrate HBP Atlas viewer into KnowledgeSpace

### ISSUE THREAD

**Issue by MBAbrams** [OpenKnowledgeSpace/KnowledgeSpace#65]
link to viewer Allen v.3: https://nip.humanbrainproject.eu/atlas/#/?dataset=5954630a-ec21-11e4-a5f8-6003088da632

It would be nice to have it integrated into the pages, but we could also have a link at this stage in the game

**Comment by slhill** [comment]
One minor issue remains on this: The page title for the Atlas says "KnowledgeSpace - Documentation".
Otherwise this looks good. There are still some performance issues that should be looked at - it's laggy.

**Comment by wawong** [comment]
The page title has been fixed.
