### ISSUE TITLE
dataspace expanded view tabs (grey out for zero results)

### ISSUE THREAD

**Issue by tgbugs** [OpenKnowledgeSpace/KnowledgeSpace#7]
Is it possible to grey out the tabs for sources that have no results in this window:
https://nye.crbs.ucsd.edu/SciCrunchKS/index.php/pages/view/NIFCELL:sao862606388#dataspace

**Comment by wawong** [comment]
I hide the sources that have no results instead. It is easier to handle it this way.

**Comment by tgbugs** [comment]
We want to be able to see all the possible sources.
