### ISSUE TITLE
Summary API does not expose clean URLs

### ISSUE THREAD

**Issue by mdupont** [OpenKnowledgeSpace/KnowledgeSpace#71]
Example: https://knowledge-space.org/API/summary/MBA:549

_overview_url_ contains "https://knowledge-space.org/index.php/pages/view/MBA:549"
The clean URL for this page (the one that should be exposed in the API) is "https://knowledge-space.org/wiki/MBA:549"

**Comment by wawong** [comment]
The overview_url in the API should have been fixed now.
