### ISSUE TITLE
! API endpoints broken (malformed JSON)

### ISSUE THREAD

**Issue by mdupont** [OpenKnowledgeSpace/KnowledgeSpace#72]
See https://knowledge-space.org/API/summary/MBA:549 for instance.

A PHP Notice is displayed and formatted as HTML before the JSON content, so the JSON cannot be parsed.

On a production system, PHP errors should not be displayed to the user, please modify the display_error PHP setting (see http://php.net/manual/en/errorfunc.configuration.php#ini.display-errors ). Also, you may want to change the error_reporting setting so only real errors are reported instead of logging notices as well (see http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting ).

**Comment by wawong** [comment]
Hi Michael,

I tried the link and it seems to be a valid json document. Can you try it again? It is possible that the backend database was down at the moment when you tried to connect to it. 

$ curl -I https://knowledge-space.org/API/summary/MBA:549
Date: Mon, 05 Dec 2016 19:19:49 GMT
Server: Apache/2.4.6 (CentOS)
X-Powered-By: PHP/5.4.45
Access-Control-Allow-Origin: *
Connection: close
Content-Type: application/json

**Comment by mdupont** [comment]
Hi,

It indeed works again since the PHP notice is not there anymore. The issue wasn't about the database, it was a PHP notice being displayed as HTML before the JSON content. The notice was about uninitialized property of an object. I should have taken a screenshot.

Basically, the server should send valid JSON, so something like:
```
{
    "overview_url":"https://knowledge-space.org/wiki/MBA:549",
    "Physiology":{
    ...
    }
}
```

Currently it does exactly the above. But if a PHP error is output, the server will send something that cannot be parsed as valid JSON:

```
<p>PHP Notice: Missing property in...</p>
{
    "overview_url":"https://knowledge-space.org/wiki/MBA:549",
    "Physiology":{
    ...
    }
}
```

Because of the HTML snippet before the JSON content, it will not be balid JSON anymore. Hence my suggestion of turning off the display_errors setting on production.

**Comment by wawong** [comment]
I turned off error display only for API.php by setting "error_reporting(0);" because we still want to see error messages elsewhere.

**Comment by mdupont** [comment]
Thanks ! 

It fixes the issue, but I think it is possible to fix it even better. The CodeIgniter framework you're using already has built-in ability to set the correct seetings for errors, see https://github.com/OpenKnowledgeSpace/KnowledgeSpace/blob/master/NeuroKS/index.php#L73

It sets the right errors levels depending on the environment, and sends errors to the screen on development, to the log on production. All it needs is having the $_SERVER["CI_ENV"] variable set on the production server to "production".

If you're using Apache it would mean putting into the .htaccess or the vhost config file the line
`SetEnv CI_ENV production`

If you're using nginx it would mean putting in the configuration file the line
`factcgi_param CI_ENV production`

This way errors in API.php would still not break the JSON output but they will be logged in the server logs, which is not the case right now with error_reporting() disabled
